### ISSUE TITLE
Deprecation warning issued by numpy over np.object

### ISSUE THREAD

**Issue by jaredjeya** [QuSpin/QuSpin#552]
When running `basis.index()` I get the following warning:

```
DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return _get_basis_index(self.states,s)
```

I believe this warning is issuing from [line 61](https://github.com/weinbe58/QuSpin/blob/5bbc3204dbf5c227a87a44f0dacf39509cba580c/quspin/basis/basis_general/_basis_general_core/general_basis_utils.pyx#L61) of `general_basis_utils.pyx` in the function `basis_int_to_python_int`, which is:

```
if basis_int_wrapper.dtype == _np.object:
```

Presumably we should just replace _np.object by object everywhere in the code to fix this warning.

**Comment by mgbukov** [comment]
this should be fixed with quspin 1.0.0
