### ISSUE TITLE
User defined symmetries in Spin language in QuSpin

### ISSUE THREAD

**Issue by adithi16** [QuSpin/QuSpin#609]
### Discussed in https://github.com/QuSpin/QuSpin/discussions/608

<div type='discussions-op-text'>

<sup>Originally posted by **adithi16** January 11, 2023</sup>
Hi, 
I am working on a 1D spin system with periodic boundary conditions.
My hamiltonian is a simple Ising model with transverse field. I understand we can implement build in symmetries like translation, parity and spin inversion. We can also define other lattice symmetries and use them to build our basis as has been shown in the documentation in a few examples.

However I would like to look at states with a particular eigenvalue for a user defined operator in spin language, for example, $\Pi_i \sigma_x^i$ which commutes with the Hamiltonian. How do I incorporate such symmetries (which have a form in spin language) while creating my basis? I do know how my symmetry takes one state to another in my full basis set. 
Is there a way in quspin to use this information to create my symmetry reduced basis? 

(I would like to work in larger system sizes and implementing a few symmetries would be beneficial.)

Any help would be really appreciated!
</div>

**Comment by mgbukov** [comment]
Hi!

Take a look at [this example](http://quspin.github.io/QuSpin/examples/example28.html#example28-label) -- it shows you how to implement the plaquette operator symmetry $W$ in the Kitaev honeycomb model; this symmetry has precisely the form $\prod_j \sigma_j$. 

In general, it is possible to implement such symmetries, for as long as the action of the symmetry on the computational basis does not lead to complex-valued coefficients: e.g., the action of $\sigma^y$ alone cannot be implemented (unless you redefine what you call the computational basis), but if your symmetry has an even number of $\sigma_y$'s (like the plaquette operator in the example), then you can use quspin.

**Comment by adithi16** [comment]
Thank you so much for referring me to this example!!
