### ISSUE TITLE
Support for aarch64 linux

### ISSUE THREAD

**Issue by MKrbm** [QuSpin/QuSpin#610]
**Is your feature request related to a problem? Please describe.**
I cannot install (conda or manyally) quspin to ubuntu docker container (aarch64) operating on M1 mac.

**Describe the solution you'd like**
I'd like to install it in either way.

**Describe alternatives you've considered**
Not yet. I tried to install manually but received an error 

```
Traceback (most recent call last):
  File "/home/user/QuSpin/setup.py", line 71, in <module>
    setup_package()
  File "/home/user/QuSpin/setup.py", line 40, in setup_package
    os.environ["CFLAGS"]=os.environ["CFLAGS"]+" -O3 -march=native"
  File "/home/user/miniconda3/envs/py39/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CFLAGS'
```
So I manually set `os.environ["CFLAGS"]` to `" -O3 -march=native"` but still got an error. (I couldn't figure out what exactly caused this error. Since error is so long, I don't put here )

**Additional context**
I could install QuSpin if I don't use docker, but I use docker container for many reasons, so not using linux-aarch64 container is the last resort.

**Comment by mgbukov** [comment]
try out the new release quspin 1.0.0 (see docs for install instructions)
