### ISSUE TITLE
Ground state of 1D t-V model

### ISSUE THREAD

**Issue by wdphy16** [QuSpin/QuSpin#616]
**Describe the physics background**
I'm trying to find the ground state of the 1D spinless fermionic t-V model. The Hamiltonian is defined as
$$H = -t \sum_{\langle i, j \rangle} \left( c^\dagger_i c_j + c^\dagger_j c_i \right) + V \sum_{\langle i, j \rangle} n_i n_j$$
on a 1D periodic chain of length `L`, the number of fermions is `Nf = L / 2`, and I use `t = 1, V = 1` in this example.

Numerical experiments on smaller systems (`L = 16, 20, 24, 28`) have shown that when `L % 4 == 0` the ground state lies in the symmetry block `k = L / 4, p = 1 or -1` (it's a semi-momentum state), which agrees with the DMRG result (implemented in ITensors.jl, and DMRG should work pretty well for this 1D system). However, when `L = 32` ED gives much higher energy (`-11.227158406700013`) than DMRG (`-15.946847944066832`).

**To reproduce**
```
from quspin.basis import spinless_fermion_basis_1d
from quspin.operators import hamiltonian

L = 32
Nf = L // 2
t = 1
V = 1
k = L // 4
p = 1

basis = spinless_fermion_basis_1d(L, Nf, kblock=k, pblock=p)
T = [(i + 1) % L for i in range(L)]
hop_l = [(-t, i, T[i]) for i in range(L)]
hop_r = [(t, i, T[i]) for i in range(L)]
nn = [(V, i, T[i]) for i in range(L)]
static = [("+-", hop_l), ("-+", hop_r), ("nn", nn)]
H = hamiltonian(static, [], basis=basis)
energy = H.eigsh(k=1, which="SA", return_eigenvectors=False)
energy = energy[0]
print("energy", energy)
```
The code takes ~30 minutes to run on my workstation.

**Expected behavior**
The ED energy should be lower than the DMRG result. The smaller systems show that the energy should be close to `-L / 2`.

I also tried to compute 10 lowest eigenvalues in eigsh. The results are `-10.28744138 -10.34682792 -10.70036303 -10.70036303 -10.76244782 -10.76244782 -10.96041776 -10.96041776 -11.22715841 -11.22715841`, and I don't think they make much sense.

**Environments**
* Ubuntu 22.04, Python 3.10.6, QuSpin 0.3.7 installed from source
* RHEL 8.5, Python 3.10.9, QuSpin 0.3.7+omp installed in conda

The issue happens on both machines, and they give the same wrong ED energy.

**Comment by wdphy16** [comment]
I tried to remove `pblock` in `spinless_fermion_basis_1d` and to use `dtype=np.complex128` in `hamiltonian`, and the energy is still wrong. This time it's `-11.694905185328125`.

Finally I tried to use `spinless_fermion_basis_general`, specifying `kblock` and not `pblock`, and the energy is `-15.946847944277561`, which looks correct. So it may be a bug in the 1d basis?

**Comment by mgbukov** [comment]
can you reproduce the odd behavior on a smaller system size?

**Comment by wdphy16** [comment]
Good to see that QuSpin 1.0.0 was published! Unfortunately, this issue still exists.

The issue exists when `L = 32`, and not when `L <= 28`. I guess it's related to some overflow.

For reference, here are the 10 lowest eigenenergies (set `k=10` in the `eigsh` in the script above):
```
L = 24: energy [ -8.58771777  -8.95964285  -9.33686971  -9.33818538  -9.33818538  -9.33994978  -9.67998842 -10.58960158 -10.92899929 -11.92911297]
L = 28: energy [-10.99367315 -11.37510944 -11.69159473 -11.69161548 -11.69161548 -11.69178004 -11.98423981 -12.78684047 -13.07780326 -13.93924902]
L = 32: energy [-10.28744138 -10.34682792 -10.70036303 -10.70036303 -10.76244782 -10.76244782 -10.96041776 -10.96041776 -11.22715841 -11.22715841]
```

I got the same results on the two machines mentioned above.
