### ISSUE TITLE
cannot import name 'ldos' from 'quspin.tools.measurements'

### ISSUE THREAD

**Issue by Habshu** [QuSpin/QuSpin#620]
**Describe the bug**

**To Reproduce**
Write a self-contained minimal code here to reproduce the bug.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Habshu** [comment]
I have installed quspin module by using "conda install -c weinbe58 quspin", tried uninstalling and installing again. Still I am getting errors " ImportError: cannot import name 'ldos' from 'quspin.tools.measurements' "
![Screenshot from 2023-02-26 10-21-04](https://user-images.githubusercontent.com/96373110/221392956-95a2f8d2-b593-44bb-91f4-f47c6b131248.png)

**Comment by mgbukov** [comment]
try the most recent version, quspin 1.0.0 (see docs for install instructions)
