### ISSUE TITLE
Checking Hermiticity of matrices

### ISSUE THREAD

**Issue by say-yas** [QuSpin/QuSpin#622]
For Hermitian matrices, the Hermiticity checks in the QuSpin are passed.
However, when we get these matrices into arrays, the check of Hermiticity on these matrices is not `True`.

For example, If we consider the example of the SYK model and add the following line, the output is `False`
`scipy.linalg.ishermitian(H_SYK.toarray())`

As Eigenvalues are all real, the Hamiltonian is certainly Hermitian. However, I wonder why applying `toarray()` produces a non-Hemritian matrix and How one can resolve this issue.

Thank you for sharing your thoughts and suggestions.

**Comment by j1ver** [comment]
This is not true. A matrix with all real eigenvalues does not need to be hermitian. The matrix [[0,1], [2,0]] has real eigenvalues, but is not hermitian.

**Comment by mgbukov** [comment]
these Qs are better suited for the discussion forum, guys!
