### ISSUE TITLE
Installation error "PackagesNotFoundError" in MacBook Pro

### ISSUE THREAD

**Issue by himanshu-PI** [QuSpin/QuSpin#624]
I'm trying to install the QuSpin on my Macbook Pro (with an M1 chip). I'm writing 

`conda install -c weinbe58 quspin`

on anaconda prompt. In return, it's saying - 

`Collecting package metadata (current_repodata.json): done`
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`
`Collecting package metadata (repodata.json): done`
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`

`PackagesNotFoundError: The following packages are not available from current channels:`

  `- quspin`

Current channels:`

  `- https://conda.anaconda.org/weinbe58/osx-arm64
  - https://conda.anaconda.org/weinbe58/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

`To search for alternate channels that may provide the conda package you're
looking for, navigate to`

    https://anaconda.org

`and use the search bar at the top of the page.`

I expanded the search to conda-forge but it still isn't working.

**Comment by Manolin-git** [comment]
With manual installation, I'm getting the following error. 

`python setup.py install --default-compiler-flags --record install_file.txt`
 

> Traceback (most recent call last):
>   File "/Users/aranyabhattacharya/Downloads/QuSpin-master/setup.py", line 71, in <module>
>     setup_package()
>   File "/Users/aranyabhattacharya/Downloads/QuSpin-master/setup.py", line 40, in setup_package
>     os.environ["CFLAGS"]=os.environ["CFLAGS"]+" -O3 -march=native"
>   File "/Users/aranyabhattacharya/anaconda3/lib/python3.10/os.py", line 680, in _getitem_
>     raise KeyError(key) from None
> KeyError: 'CFLAGS'
> (base) aranyabhattacharya@Aranyas-MacBook-Pro QuSpin-master % conda activate myenv
> (myenv) aranyabhattacharya@Aranyas-MacBook-Pro QuSpin-master % python setup.py install --default-compiler-flags --record install_file.txt
> Traceback (most recent call last):
>   File "/Users/aranyabhattacharya/Downloads/QuSpin-master/setup.py", line 71, in <module>
>     setup_package()
>   File "/Users/aranyabhattacharya/Downloads/QuSpin-master/setup.py", line 40, in setup_package
>     os.environ["CFLAGS"]=os.environ["CFLAGS"]+" -O3 -march=native"
>                          ~~~~~~~~~~^^^^^^^^^^
>   File "<frozen os>", line 679, in _getitem_
> KeyError: 'CFLAGS'
> (myenv) aranyabhattacharya@Aranyas-MacBook-Pro QuSpin-master % python setup.py install --default-compiler-flags --record install_file.txt
> Traceback (most recent call last):
>   File "/Users/aranyabhattacharya/Downloads/QuSpin-master/setup.py", line 71, in <module>
>     setup_package()
>   File "/Users/aranyabhattacharya/Downloads/QuSpin-master/setup.py", line 40, in setup_package
>     os.environ["CFLAGS"]=os.environ["CFLAGS"]+" -O3 -march=native"
>                          ~~~~~~~~~~^^^^^^^^^^
>   File "<frozen os>", line 679, in _getitem_
> KeyError: 'CFLAGS'

**Comment by mgbukov** [comment]
It is difficult for me to figure out what is going on from the error
message. @weinbe58: do you have an idea what might be causing this?

I am currently busy with a number of things, but I have set a reminder to
come back to this when I have more time and try to compile quspin from
scratch on my new M1 macbook.

**Comment by iarayad** [comment]
`conda install quspin` doesn't work in linux either, and `conda install -c weinbe58 quspin` leads to several package inconsistencies with Python 3.11.

**Comment by mgbukov** [comment]
I'm afraid we don't yet have a quspin release for python 3.11; py 3.10 is
the last one we did.

If needed be, you can try compiling quspin for py3.11 from the source code
(see installation manual)

**Comment by mgbukov** [comment]
try out the most recent release quspin 1.0.0 (see docs for installation(
