### ISSUE TITLE
Correction in `quant_fluct` documentation

### ISSUE THREAD

**Issue by say-yas** [QuSpin/QuSpin#633]
Hello,

The provided example in `quant_fluct` in [here](http://quspin.github.io/QuSpin/generated/quspin.operators.hamiltonian.html#quspin.operators.hamiltonian.quant_fluct) reads `H_fluct = H.quant_fluct(V,time=0,diagonal=False,check=True)`. 
This is, however, not correct as the `diagonal` is not one of the parameters of this function;
 instead, `enforce_pure` should be added. 

Thank you for making the change.

**Comment by mgbukov** [comment]
please, submit this change as a pull request. Thanks!
