### ISSUE TITLE
Check Hermiticity of a matrix

### ISSUE THREAD

**Issue by say-yas** [QuSpin/QuSpin#634]
Hello,

I am working with a Hamiltonian $H=i \sigma_{y}$. By definition, this Hamiltonian is Hermitian. 
However, implementing this Hamiltonian raises an error 
`TypeError: Hamiltonian not hermitian! To turn this check off set check_herm=False in hamiltonian.`

Here is a small script to generate the above error.
```
L=6
h_y=[[1j,i] for i in range(L)]
# define spin static and dynamic lists
static_spin =[["y",h_y]] # static part of H
print(static_spin)
dynamic_spin =[] 
basis_spin = spin_basis_1d(L=L) 

# build spin Hamiltonians
H_spin=hamiltonian(static_spin,dynamic_spin,basis=basis_spin,dtype=np.complex128,check_herm=True,check_symm=False) 
```
In principle, the code complains about $\sigma_{y}$ by`The following static operator strings contain non-hermitian couplings: ['y']`.

**Comment by JiahaoYao** [comment]
The operator sigma_y is Hermitian, whereas the operator i times sigma_y is not Hermitian.
