### ISSUE TITLE
Create a release or a tag with the latest version on GitHub

### ISSUE THREAD

**Issue by MoiseRousseau** [QuSpin/QuSpin#643]
Hi!

I works at Calcul Quebec and the Digital Research Alliance of Canada where we manage national HPC clusters. We also have a organization wide wheelhouse where we push optimized wheels for our cluster. I would like to add QuSpin to our wheelhouse but it requires a versioning system up to date. Can you create an officiel tag or release on GitHub with the latest change ? Or push the up to date sources on PyPi ? On Anaconda, the latest version seems to be 0.3.7 (https://anaconda.org/weinbe58/quspin) but I can't download the sources. Are they available ?

Moise

**Comment by mgbukov** [comment]
quspin 1.0.0 is now on pypi
