### ISSUE TITLE
Bug in hamiltonian.rdot() in module quspin.operators

### ISSUE THREAD

**Issue by sRb-root** [QuSpin/QuSpin#645]
Hello, 

I came across an apparent bug in the hamiltonian rdot operator. The following is a simple demonstration:

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
from quspin.basis import boson_basis_1d
from quspin.operators import hamiltonian

basis=boson_basis_1d(L=4, Nb=1)
Jn = [[1,i] for i in range(4)]
static = [["n", Jn]]

H = hamiltonian(static, [], basis=basis, check_herm=False, check_symm=False, check_pcon=False)

V = [1,0,0,0]

op_dot = H.dot(V)    #this works fine

op_rdot = H.rdot(V)   #this throws error
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" 

Error message:

Traceback (most recent call last):
  File "/home/sourav/Desktop/test_rdot.py", line 16, in <module>
    op_rdot = H.rdot(V)
  File "/home/sourav/anaconda3/envs/qs/lib/python3.9/site-packages/quspin/operators/hamiltonian_core.py", line 785, in rdot
    return self.transpose().dot(V,time=times,check=check,out=out.T,overwrite_out=overwrite_out,a=a)
AttributeError: 'NoneType' object has no attribute 'T'

Please look into it.

Thanks, keep up the awesome work!

**Comment by mgbukov** [comment]
I guess, `V` has to be a `np.array` for `rdot` to work.
