### ISSUE TITLE
Coupling tensor in Example 25 needs to be anti-symmetric

### ISSUE THREAD

**Issue by timbode** [QuSpin/QuSpin#652]
The coupling tensor in [Example 25](https://github.com/QuSpin/QuSpin/blob/master/docs/examples/example25.html) needs to be anti-symmetric (or alternatively, the loops should run only over `i < j < k < l`). In other words, the Hamiltonian as defined in the code is not correct (non-Hermitian).

**Comment by mgbukov** [comment]
you're probably right; feel free to make the change and if it looks alright (and quspin doesn't throw an error) go ahead and make a pull request to update the example :)
