### ISSUE TITLE
How to create a fermionic basis with conservation of total particle number in QuSpin?

### ISSUE THREAD

**Issue by HaoJieShen** [QuSpin/QuSpin#655]
**Description**
I mean, how can I make a basis with fixed Nf, including all the Nf=(i, Nf-i)

**Links**
https://quspin.github.io/QuSpin/generated/quspin.basis.spinful_fermion_basis_general.html#quspin.basis.spinful_fermion_basis_general

**Comment by mgbukov** [comment]
please state questions in the discussion forum ;)
