### ISSUE TITLE
Manual installation: boost issue

### ISSUE THREAD

**Issue by miflynn** [QuSpin/QuSpin#666]
I'm installing QuSpin manually on a computing cluster where Anaconda/miniconda installation is strongly discouraged. I've installed the prerequisite packages and tried to run "python setup.py install --default-compiler-flags". This terminates with the error message:

> /project/6049303/QuSpin/quspin/basis/basis_general/_basis_general_core/source/bits_info.h:5:10: fatal error:
> boost/multiprecision/cpp_int.hpp: No such file or directory
>     5 | #include "boost/multiprecision/cpp_int.hpp"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.

This is, presumably, due to issues associated with headers in the boost library, but I don't know how to fix this bug. The only reference to these headers on the installation page for quspin doesn't offer a fix and is quite vague. How can this be fixed?

**Comment by mgbukov** [comment]
yes, it looks like your cpp compiler cannot find the path to your boost library. Have you tried exporting the path to boost (I assume you downloaded the library yourself) explicitly before you run the python install command? I remember I had a similar issue long time ago and exporting the path explicitly to where this header files was on my laptop did the job. 

If it turns out you need to pass the path to the cpp compiler directly, you can check [`setup.py`](https://github.com/QuSpin/QuSpin/blob/master/setup.py#L35) where some omp options are passed using flags, and add extra ones.  

Btw, boost is needed for large integer support (i.e., system sizes >64 sites); if you don't intend to use this functionality, it might be possible to decouple the `bits_info.h' header from the rest fo the code but this may take time to do cuz there's no automatic way of doing this. Anyway, I mention this as a last resort.

**Comment by miflynn** [comment]
Thanks @mgbukov for the fast response - I've tried exporting the boost path and that doesn't seem to have helped. Could you clarify  how I could modify setup.py? I've taken a look at it in a text editor in my terminal and I don't have a clear understanding of what's going on. I'm fairly inexperienced with these sorts of problems but I don't see any sort of flag that looks reasonable to modify.

**Comment by mgbukov** [comment]
if exporting the PATH didn't help, it likely means that the cpp compiler called during the installation is different from the default one (the one that sees the PATH variable content). 

I don't remember quite what I did back then, but you can try either of these:
1) in `bits_info.h` replace

`#include "boost/multiprecision/cpp_int.hpp"`

by 

`#include "PATH to boost/multiprecision/cpp_int.hpp"`

2) in line 40 of [setup.py](https://github.com/QuSpin/QuSpin/blob/master/setup.py#L40) we pass some extra arguments to the compiler; you can add in the string

` +" -I<path to boost headers>"`

**Comment by mgbukov** [comment]
I think at this stage it's probably best to contact whoever is administering your cluster and ask them for help.

After all, nothing prevents u from downloading miniconda in your home directory and installing quspin the standard way, and if they really want u not to do that, maybe they can take a look at what's wrong with the compilers, etc?

**Comment by miflynn** [comment]
Thanks @mgbukov - I did exactly that and things have moved along significantly. The compilation of quspin now runs to completion, but there is a new problem which comes up when importing the library. I'll copy the error message here but since this is a new problem, let me know if I should close this thread and open a separate one:

> >>> import quspin
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/project/6049303/moflynn/QuSpin/quspin/__init__.py", line 3, in <module>
>     from . import operators
>   File "/project/6049303/moflynn/QuSpin/quspin/operators/__init__.py", line 54, in <module>
>     from .quantum_operator_core import *
>   File "/project/6049303/moflynn/QuSpin/quspin/operators/quantum_operator_core.py", line 3, in <module>
>     from ..basis import spin_basis_1d as _default_basis
>   File "/project/6049303/moflynn/QuSpin/quspin/basis/__init__.py", line 130, in <module>
>     from .basis_1d import *
>   File "/project/6049303/moflynn/QuSpin/quspin/basis/basis_1d/__init__.py", line 1, in <module>
>     from .spin import spin_basis_1d
>   File "/project/6049303/moflynn/QuSpin/quspin/basis/basis_1d/spin.py", line 1, in <module>
>     from ._basis_1d_core import hcp_basis,hcp_ops
>   File "/project/6049303/moflynn/QuSpin/quspin/basis/basis_1d/_basis_1d_core/__init__.py", line 1, in <module>
>     from . import hcp_basis,hcp_ops
> ImportError: cannot import name 'hcp_basis' from partially initialized module 'quspin.basis.basis_1d._basis_1d_core' (most likely due to a circular import) (/project/6049303/moflynn/QuSpin/quspin/basis/basis_1d/_basis_1d_core/__init__.py)


I'm not sure why this is coming up, but maybe it's a bug that's been seen before.

**Comment by mgbukov** [comment]
I haven't seen this before :(

Maybe something went wrong with compiling the cpp code?

**Comment by mgbukov** [comment]
we now have quspin 1.0.0 (see docs on how to install); if this issue still persists, feel free to reopen ;)
