### ISSUE TITLE
Wrong documentation reference in quspin.operators.hamiltonian.eigvalsh

### ISSUE THREAD

**Issue by hz-xiaxz** [QuSpin/QuSpin#673]
**Description**
Add descirption of the issue here:
 * Questions
 * typos: the function `eigvalsh` doesn't really refer to the `numpy.linalg.eigvalsh`, but `scipy.linalg.eigvalsh` is used. These two functions have different parameters.
 * Proposals new Documentation

**Links**
Provide a link to the webpage with the issue if applicable.
https://quspin.github.io/QuSpin/generated/quspin.operators.hamiltonian.html?highlight=eigvalsh#quspin.operators.hamiltonian.eigvalsh

**Comment by mgbukov** [comment]
this was fixed with quspin 1.0.0
