### ISSUE TITLE
Imaginary spectrum for a non-hermitian Hamiltonian

### ISSUE THREAD

**Issue by SantiagoTB** [QuSpin/QuSpin#699]
Hello
I am trying to diagonalize the non-hermitian hamiltonian $H =-\sum_{j}^{L-1}\sigma_{j}^{z}\sigma_{j+1}^{z} -(h+i\frac{\gamma}{2})\sum_{j}^{L}\sigma_{j}^{x}$. If I am correct, Since $H$ is non-hermitian, it has a complex spectrum ($\lambda_{i} = a_{i} + ib_{i})$. However, When I try to diagonalize $H$ using the function ".eigh()" I obtain a real spectrum.

**Comment by mgbukov** [comment]
this is b/c `eigh()` is only applied to hermitian operators (hence the h in `eigh`); please see the scipy/numpy doc on how to diagonalize nonhermitian operators.
