### ISSUE TITLE
Entanglement Entropy of Ising Model H=-JZZ-hX

### ISSUE THREAD

**Issue by hcut** [QuSpin/QuSpin#712]
### Discussed in https://github.com/QuSpin/QuSpin/discussions/711

<div type='discussions-op-text'>

<sup>Originally posted by **hcut** October  7, 2024</sup>
Entanglement entropy of  Ising model  $H=-JZZ-hX$ 

![3](https://github.com/user-attachments/assets/b1aa39fb-1ff0-4af7-8598-b72f84c651e4)

is given as (for $J=h=1, c=0.5$) for subsystem x, S(x) =

![1](https://github.com/user-attachments/assets/093e9328-7096-486d-8efe-6b808b0009c0)

Which looks  like as 

![2](https://github.com/user-attachments/assets/f792bc82-c3c1-4234-8b3a-78414f456efc)

I am trying to reproduce the same results, but I am not getting even close to this figures, I am getting the following figure

![4](https://github.com/user-attachments/assets/07613792-208a-4676-b7b1-3ce90ca44605)

I am calculating as follows : 

     ...
     e_m,v_m=H.eigsh(k=1,which="SA",maxiter=1E4,pars=dict(h0=1.0,h1=H_x),return_eigenvectors=True)
     def get_ee(j):
            subsys=[i for i in range(j)] 
            Sent_dict = ent_entropy(v_m, basis, chain_subsys=subsys, return_rdm='A')  
            ee = Sent_dict['Sent_A']
           return ee 
    #
    for n in range(L):   
            ee=get_ee(n)       
         #   print(ee)

 It prints the subsytems as

         [0]
         [0, 1]
         [0, 1, 2]
         [0, 1, 2, 3]
         [0, 1, 2, 3, 4]
         ........
         

I think I am doing something wrong in defining the subsystems at each step. 

I will be grateful in somebody can help me here ?

</div>

**Comment by mgbukov** [comment]
please post this Q in the discussion forum ;)

https://github.com/QuSpin/QuSpin/discussions

closing it here
