### ISSUE TITLE
Developer install instructions do not work - repository not found

### ISSUE THREAD

**Issue by jaredjeya** [QuSpin/QuSpin#717]
**Describe the bug**
The "Quspin Workspace" respository doesn't seem to exist.

**To Reproduce**
Run `git clone https://github.com/QuSpin/QuSpin-workspace` as described in the instructions.

**Expected behaviour**
Git clones the repository.

**Actual behaviour**
```
Cloning into 'QuSpin-workspace'...
remote: Repository not found.
fatal: repository 'https://github.com/QuSpin/QuSpin-workspace/' not found
```

The link in the documentation (https://github.com/QuSpin/QuSpin-workspace) gives a 404 error.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mgbukov** [comment]
sorry about that -- we forgot to make the repo public; now it is.

**Comment by jaredjeya** [comment]
Thanks! Working now

**Comment by jaredjeya** [comment]
Unfortunately I've run up against an error trying to build it.

While trying to `> pip install -e QuSpin-Extensions/ -v`, I'm getting `FileNotFoundError: Could not find boost headers`. This is despite attempting to install boost using both pip and conda.

I'm using a Conda virtual environment but otherwise I've only run the commands in the instructions.

I'm on Windows 10, Python 3.12.

Full output of `pip list`:
```
Package               Version     Editable project location
--------------------- ----------- ----------------------------------------------------------------------------------------------------
blurhash              1.1.4
boost                 0.1
certifi               2024.8.30
charset-normalizer    3.3.2
decorator             5.1.1
greenlet              3.1.1
idna                  3.10
Mastodon.py           1.8.1
numpy                 2.1.2
parallel-sparse-tools 0.2.2       C:\Users\jared\OneDrive - University of Leeds\PyCharmProjects\QuSpin-workspace\parallel-sparse-tools
pip                   24.2
python-dateutil       2.9.0.post0
python-magic-bin      0.4.14
requests              2.32.3
scipy                 1.14.1
setuptools            75.1.0
six                   1.16.0
SQLAlchemy            2.0.35
typing_extensions     4.12.2
urllib3               2.2.3
wheel                 0.44.0
```

**Comment by jaredjeya** [comment]
I was able to fix this by pointing `$Env:BOOST_ROOT = <path to boost>`, where in this case it was `...\miniconda3\envs\py_quspin_dev\Library`.

Should probably be in the docs that this might be necessary (I'm happy to open a PR to do that).

**Comment by weinbe58** [comment]
Yes feel free to open a PR! I wanted to split up the package to improve contributions on the python code base!
