### ISSUE TITLE
Setting the environment variable os.environ['OMP_NUM_THREADS'] > 64

### ISSUE THREAD

**Issue by hcut** [QuSpin/QuSpin#728]
I am running the program on a HPC cluster having 128 cores, so I want to utilize all the possible cores, but  I am getting the following error message on setting the  `os.environ['OMP_NUM_THREADS']="128"` and  
`os.environ['MKL_NUM_THREADS']="128"`

`Error.  nthreads cannot be larger than environment variable "NUMEXPR_MAX_THREADS" (64)`

Could you please help me with this?

**Comment by weinbe58** [comment]
This is an issue with numexpr I would submit an issue there.
